name: 'Publish to Powershell Gallery'

on: 
  release:
    types: published
jobs:
  publish:    
    name: Set-PsEnv Deployment
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Deploy to PSGallery
      env:
        PSGALLERY_TOKEN: ${{secrets.PowershellGallery}}        
      run: .github\workflows\Deploy.ps1
      shell: pwsh